# Generated by Django 3.2.6 on 2021-08-17 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('regiao', models.CharField(choices=[('Atlantico', 'Atlantico'), ('Central', 'Central'), ('Sudeste', 'Sudeste'), ('Noroeste', 'Noroeste'), ('Pácifico', 'Pácifico'), ('Sudoeste', 'Sudoeste')], default='Atlantico', max_length=10)),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=50)),
                ('dataInicio', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 11, 19, 52, 171564, tzinfo=utc))),
                ('mostrar', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%y/%m/%d/')),
                ('Cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.cidade')),
            ],
        ),
    ]
