# Generated by Django 3.2.6 on 2021-08-17 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 11, 26, 42, 133713, tzinfo=utc)),
        ),
    ]
