# Generated by Django 3.2.6 on 2021-08-17 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_time_datainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='estadio',
            field=models.ImageField(blank=True, upload_to='etadios/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='time',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 12, 35, 24, 138516, tzinfo=utc)),
        ),
    ]
