# Generated by Django 3.2.6 on 2021-08-18 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210817_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 13, 13, 40, 48363, tzinfo=utc)),
        ),
    ]
