# Generated by Django 3.2.5 on 2021-09-08 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_time_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 12, 41, 16, 696526, tzinfo=utc)),
        ),
    ]
